#!/bin/sh

PATH='/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'

LOG_DIR=/var/opt/maccel/logs
mkdir -p $LOG_DIR

chown -v :maccel /sys/module/maccel/parameters/* &>$LOG_DIR/chown
chown -v :maccel /dev/maccel &>$LOG_DIR/chown
chmod g+r /dev/maccel &>$LOG_DIR/chmod

# For persisting parameters values across reboots
RESET_SCRIPTS_DIR=/var/opt/maccel/resets
mkdir -p $RESET_SCRIPTS_DIR
chown -v :maccel $RESET_SCRIPTS_DIR
chmod -v g+w "$RESET_SCRIPTS_DIR"
ls $RESET_SCRIPTS_DIR/set_last_*_value.sh | xargs cat | sh &>$LOG_DIR/reset-scripts
ls $RESET_SCRIPTS_DIR/* | xargs chown -v :maccel &>$LOG_DIR/reset-scripts
ls $RESET_SCRIPTS_DIR/* | xargs chmod -v g+w &>$LOG_DIR/reset-scripts
