name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_core_function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Test acceleration function
        run: make test
      - name: Test CLI
        run: cargo test --all
      - name: Test install scripts
        run: sh tests/dkms_cleanup.test.sh
