name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_core_function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test acceleration function
        run: make test
      - name: Test CLI
        run: cargo test --all
